export const HOME_VIDEO_REQUEST = "HOME_VIDEO_REQUEST";
export const HOME_VIDEO_SUCCESS = "HOME_VIDEO_SUCCESS";
export const HOME_VIDEO_FAIL = "HOME_VIDEO_FAIL";

export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST";
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS";
export const SELECTED_VIDEO_FAIL = "SELECTED_VIDEO_FAIL";

export const RELATED_VIDEO_REQUEST = "RELATED_VIDEO_REQUEST";
export const RELATED_VIDEO_SUCCESS = "RELATED_VIDEO_SUCCESS";
export const RELATED_VIDEO_FAIL = "RELATED_VIDEO_FAIL";
